# Generated by Django 3.0.6 on 2020-05-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='wardno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
